<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1E7MQ28" failures="1" tests="1" name="Test" time="0.34" errors="0" timestamp="2023-12-23T13:26:41 IST">
  <testcase classname="dataprovider_with_xlfile.Testclass" name="login" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at dataprovider_with_xlfile.Xl_data.xldata(Xl_data.java:34)
at dataprovider_with_xlfile.Xl_data.getdata(Xl_data.java:48)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
